---
- name: Restart Promtail Service
  hosts: pe_mains
  become: yes
  tasks:
    - name: Restart Promtail
      systemd:
        name: promtail
        state: started
      ignore_errors: yes  # Ignore errors if Promtail service does not exist on the host